### ISSUE TITLE
Problems just after initial installation

### ISSUE THREAD

**Issue by mik01aj** [randylien/generator-react-gulp-browserify#18]
Hi, I just created a new project using `yo react-gulp-browserify`. I run `gulp watch` and get the following output:

````
[12:17:28] Using gulpfile ~/code/react-frontend/gulpfile.js
[12:17:28] Starting 'html'...
[12:17:28] Starting 'scripts'...
[12:17:28] Starting 'bower'...
[12:17:28] Finished 'bower' after 1.34 ms
[12:17:28] Starting 'serve'...
[12:17:28] Webserver started at http://localhost:9000
[12:17:28] Finished 'serve' after 231 ms
[12:17:28] all files 1.87 kB
[12:17:28] Finished 'html' after 501 ms
[12:17:30] Finished 'scripts' after 2.04 s
[12:17:30] Starting 'bundle'...

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)
    at Transform.onerror (/Users/mik01aj/code/react-frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:95:17)
    at Transform.<anonymous> (/Users/mik01aj/code/react-frontend/node_modules/gulp-useref/index.js:76:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/mik01aj/code/react-frontend/node_modules/gulp-useref/index.js:66:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/mik01aj/code/react-frontend/node_modules/gulp-useref/index.js:44:36)
    at Array.forEach (native)
```

I don't understand those error messages (https://github.com/gulpjs/gulp/issues/881), but maybe you'll do. Certainly that's something that shouldn't happen :)

**Comment by mik01aj** [comment]
Ah, I got it, I had to remove the bower stuff from index.html.

Btw, why are you shipping bower with the generator without mentioning it in the doc? I don't need Bower, because with browserify I can include CommonJS modules.

**Comment by mik01aj** [comment]
PS. Adding info about what's optional would be very nice as well. I made a pull request with a README update: https://github.com/randylien/generator-react-gulp-browserify/pull/19
