### ISSUE TITLE
Newly generated app is not functional

### ISSUE THREAD

**Issue by cachafla** [randylien/generator-react-gulp-browserify#44]
I was under impression that all of the initial choices for configuring my project were optional, however I am unable to get a running project out of the box.

My environment is:

```
$ node -v
v0.12.3

$ npm -v
2.9.1
```

I followed the instructions to install the generator and proceeded to configure a new project like this:

```
? What more would you like? Sass with Compass, Bootstrap, Modernizr, Jest for unit tests
```

After it finishes I try to get it running with `gulp watch` but this is what I get:

```
$ gulp watch
[12:17:45] Using gulpfile ~/Code/Vink/vink-admin/gulpfile.js
[12:17:45] Starting 'html'...
[12:17:45] Starting 'fonts'...
[12:17:45] Starting 'sass'...
[12:17:46] Starting 'scripts'...
[12:17:46] Starting 'bower'...
[12:17:46] Finished 'bower' after 842 μs

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn sass ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

Seems like the sass integration is broken? I'm not sure what to do next as I'm just learning about gulp.

**Comment by diroussel** [comment]
I get the same error.

$ npm -v
2.10.0
 $ node -v
v0.12.2

**Comment by randylien** [comment]
Thanks for your report. Let me check.

**Comment by maxosprojects** [comment]
same here.
"Sass with Compass, Jest for unit tests"
$ npm -v
2.7.5
$ node -v
v0.12.2

**Comment by mkliu** [comment]
+1

**Comment by stuartmemo** [comment]
Having this issue as well. Anyone have any idea of a temporary workaround?

**Comment by randylien** [comment]
Hi all, may I have more information about your environments like the version of ruby, sass, node and npm ?
Thanks.

**Comment by stuartmemo** [comment]
OSX 10.10.2
Ruby 2.1.3
Sass 3.4.14
Node 0.12.0
npm 2.5.1

I've tried to switching to libsass, but same issue.

**Comment by randylien** [comment]
@stuartmemo please try to run this command `npm install gulp-ruby-sass@1.0.5` to install `gulp-ruby-sass' in your project folder and try again.

**Comment by stuartmemo** [comment]
@randylien No difference sorry.

**Comment by stuartmemo** [comment]
Ok, think I figured it out. I believe that this error happens if you reference an non-existent file in your HTML build tags. So, for example, I had.
```html
 <script src="bower_components/jquery/dist/jquery.js"></script>
```
But my dist directory inside `bower_components` didn't exist.

Hope that helps!

**Comment by runlevelsix** [comment]
Another possible fix is to downgrade Node to 0.10. Once I did that everything seemed to work.

**Comment by randylien** [comment]
Thanks @runlevelsix , it seems like people will encounter dependency issues in node 0.12.
I will update this repo and mention this in README.

**Comment by knutmarius** [comment]
Any fix for this that does not involve downgrading to node 0.10?

**Comment by randylien** [comment]
I updated sass task to fix this issue.
Please try @0.0.29.
