### ISSUE TITLE
Unselecting all choices during generator creation causes an error regarding sass

### ISSUE THREAD

**Issue by bobbydavid** [randylien/generator-react-gulp-browserify#53]
Immediately after installing, when I try to run `gulp watch`, I get:

    [18:13:05] Warning: gulp version mismatch:
    [18:13:05] Global gulp is 3.9.0
    [18:13:05] Local gulp is 3.8.11
    [18:13:06] Using gulpfile ~/tmp/pubsub-demo/gulpfile.js
    [18:13:06] Starting 'html'...
    [18:13:06] Starting 'fonts'...
    [18:13:06] Starting 'sass'...
    [18:13:06] 'sass' errored after 48 ms
    [18:13:06] TypeError: Arguments to path.join must be strings
        at Object.posix.join (path.js:488:13)
        at Object.module.exports (/usr/local/google/home/rdm/tmp/pubsub-demo/node_modules/gulp-ruby-sass/index.js:56:15)
        at Gulp.<anonymous> (/usr/local/google/home/rdm/tmp/pubsub-demo/gulpfile.js:34:17)
        at module.exports (/usr/local/google/home/rdm/tmp/pubsub-demo/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/usr/local/google/home/rdm/tmp/pubsub-demo/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
        at Gulp.Orchestrator._runStep (/usr/local/google/home/rdm/tmp/pubsub-demo/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
        at Gulp.Orchestrator.start (/usr/local/google/home/rdm/tmp/pubsub-demo/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
        at /usr/local/google/home/rdm/usr/lib/node_modules/gulp/bin/gulp.js:129:20
        at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
    [18:13:06] Finished 'fonts' after 110 ms
    [18:13:06] all files 1.77 kB
    [18:13:06] Finished 'html' after 230 ms

I suspect it's because I unchecked `sass` as during generation?

**Comment by randylien** [comment]
because the new ruby-sass change its api.
Please try 0.029.
