### ISSUE TITLE
Sass compiler error

### ISSUE THREAD

**Issue by BogdanMihaiNicolae** [randylien/generator-react-gulp-browserify#62]
I'm having trouble with SASS compiler. I get the error below.
I'm on Windows 10 with Node v4.2.4. 
Can you help me?
````
[12:38:45] Starting 'sass'...
[12:38:45] Starting 'clean'...
[12:38:45] 'clean' errored after 8.42 ms
[12:38:45] Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\bogda\Desktop\tic-tac-toe\dist\scripts'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:334:11)
    at rmdirSync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:324:7)
    at Function.rimrafSync [as sync] (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:295:9)
    at C:\Users\bogda\Desktop\tic-tac-toe\node_modules\del\index.js:63:10
    at Array.forEach (native)
    at Function.module.exports.sync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\del\index.js:54:30)
    at Gulp.<anonymous> (C:\Users\bogda\Desktop\tic-tac-toe\gulpfile.js:108:12)
    at module.exports (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\orchestrator\index.js:134:8)
    at Gulp.<anonymous> (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\gulp\index.js:36:18)
    at Gaze.<anonymous> (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\glob-watcher\index.js:18:14)
    at emitTwo (events.js:87:13)
[BS] Reloading Browsers...
[12:38:45] 'sass' is not recognized as an internal or external command,
operable program or batch file.
[12:38:45] all files 0 B
[12:38:45] Finished 'sass' after 84 ms
[12:38:47] Starting 'sass'...
[12:38:47] Starting 'clean'...
[12:38:47] 'clean' errored after 6.79 ms
[12:38:47] Error: EPERM: operation not permitted, unlink 'C:\Users\bogda\Desktop\tic-tac-toe\dist\scripts\app.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at rimrafSync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:297:17)
    at C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:332:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:331:26)
    at rmdirSync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:324:7)
    at fixWinEPERMSync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:204:5)
    at Function.rimrafSync [as sync] (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\rimraf\rimraf.js:302:28)
    at C:\Users\bogda\Desktop\tic-tac-toe\node_modules\del\index.js:63:10
    at Array.forEach (native)
    at Function.module.exports.sync (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\del\index.js:54:30)
    at Gulp.<anonymous> (C:\Users\bogda\Desktop\tic-tac-toe\gulpfile.js:108:12)
    at module.exports (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\bogda\Desktop\tic-tac-toe\node_modules\orchestrator\index.js:214:10)
[BS] Reloading Browsers...
[12:38:47] 'sass' is not recognized as an internal or external command,
operable program or batch file.
[12:38:47] all files 0 B
[12:38:47] Finished 'sass' after 69 ms
````

**Comment by rapasoft** [comment]
I have exactly the same problem. But I am not using SASS compiler, only watching CSS for changes. It only fails when trying to reload the CSS file

```
[09:19:14] Error: EPERM: operation not permitted, unlink 'C:\dev\work\AtEleven\src\main\js\dist\scripts\app.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at rimrafSync (C:\dev\work\AtEleven\src\main\js\node_modules\del\node_modules\rimraf\rimraf.js:297:17)
    at C:\dev\work\AtEleven\src\main\js\node_modules\del\node_modules\rimraf\rimraf.js:332:5
    at Array.forEach (native)
    at rmkidsSync (C:\dev\work\AtEleven\src\main\js\node_modules\del\node_modules\rimraf\rimraf.js:331:26)
    at rmdirSync (C:\dev\work\AtEleven\src\main\js\node_modules\del\node_modules\rimraf\rimraf.js:324:7)
    at fixWinEPERMSync (C:\dev\work\AtEleven\src\main\js\node_modules\del\node_modules\rimraf\rimraf.js:204:5)
    at Function.rimrafSync [as sync] (C:\dev\work\AtEleven\src\main\js\node_modules\del\node_modules\rimraf\rimraf.js:302:28)
    at C:\dev\work\AtEleven\src\main\js\node_modules\del\index.js:63:10
    at Array.forEach (native)
    at Function.module.exports.sync (C:\dev\work\AtEleven\src\main\js\node_modules\del\index.js:54:30)
    at Gulp.<anonymous> (C:\dev\work\AtEleven\src\main\js\gulpfile.js:109:12)
    at module.exports (C:\dev\work\AtEleven\src\main\js\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\dev\work\AtEleven\src\main\js\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\dev\work\AtEleven\src\main\js\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
[BS] Reloading Browsers...
Error: EPERM: operation not permitted, stat 'C:\dev\work\AtEleven\src\main\js\dist\scripts\app.js'
    at Error (native)
Error: EPERM: operation not permitted, stat 'C:\dev\work\AtEleven\src\main\js\dist\scripts\app.js'
    at Error (native)
Error: EPERM: operation not permitted, stat 'C:\dev\work\AtEleven\src\main\js\dist\scripts\app.js'
    at Error (native)
Error: EPERM: operation not permitted, stat 'C:\dev\work\AtEleven\src\main\js\dist\scripts\app.js'
    at Error (native)
```

**Comment by codeofsumit** [comment]
`'sass' is not recognized as an internal or external command,`

you need sass.
`gem install sass`

for that to work you need to have ruby installed.

**Comment by magicodeuk** [comment]
I have sass installed and it still gives these same errors, except wthout the  line `'sass' is not recognized as an internal or external command,`

**Comment by magicodeuk** [comment]
`gulp` works fine but `gulp watch` gives a load of errors about file access. I'm on Windows 10 and trying to run this ootb.

**Comment by magicodeuk** [comment]
```
Error: EPERM: operation not permitted, open 'E:\PHPStormProjects\rt2\dist\scripts\app.js'
    at Error (native)
[BS] Reloading Browsers...
Error: EPERM: operation not permitted, stat 'E:\PHPStormProjects\rt2\dist\scripts\app.js'
    at Error (native)
Error: EPERM: operation not permitted, stat 'E:\PHPStormProjects\rt2\dist\scripts\app.js'
    at Error (native)
```
